=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/classes/config/dao/gwssi-database.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT table (database?, default-config?, sort-name?, table-info, column*, primary-key?, index*, foreign-key*, function*)>

<!-- 表信息定义 !-->
<!-- description:字段描述 !-->
<!ELEMENT table-info (description?)>

<!-- 表名称 !-->
<!ATTLIST table-info name CDATA #REQUIRED>

<!-- 对应表的类名称:缺省为cn.gwssi.app.database.目录.表名称 !-->
<!ATTLIST table-info class-name CDATA #IMPLIED>

<!-- 处理缓存记录的类名称 !-->
<!ATTLIST table-info cache-class CDATA #IMPLIED>

<!-- 复核标志：true=修改需要复核、false=不需要复核 !-->
<!ATTLIST table-info check-flag (true | false) "false">

<!-- 保存历史数据的标志：true=修改需要把原始数据保存到历史表、false=不需要保存到历史表 !-->
<!ATTLIST table-info backup-flag (true | false) "false">

<!-- 数据表检测的周期 !-->
<!ATTLIST table-info check-time CDATA  #IMPLIED>


<!-- 字段定义 !-->
<!-- description:字段描述 !-->
<!ELEMENT column EMPTY>

<!-- 字段名称 !-->
<!ATTLIST column name CDATA #REQUIRED>

<!-- 字段对应的数据项名称 !-->
<!ATTLIST column java-name CDATA #IMPLIED>

<!-- 数据类型 !-->
<!ATTLIST column data-type (
		integer | long | decimal | char | varchar | 
		date | time | timestamp | binary
	) "char" >

<!-- 字段长度 !-->
<!ATTLIST column length CDATA #IMPLIED>

<!-- 小数位长度 !-->
<!ATTLIST column fraction-length CDATA #IMPLIED>

<!-- 字段是否能够空 !-->
<!ATTLIST column not-null (true | false) "false">

<!-- 空内容是否转换成NULL !-->
<!ATTLIST column empty-is-null (true | false) "false">

<!-- 缺省值 !-->
<!ATTLIST column default CDATA #IMPLIED>

<!-- 值是否唯一 !-->
<!ATTLIST column unique (true|false) "false">

<!-- 数据内容的来源 !-->
<!ATTLIST column value-from (input | generate | sequence | autoincrement | UUID) "input">

<!-- 转换函数 !-->
<!ATTLIST column func-name CDATA #IMPLIED>

<!-- 取值范围 !-->
<!ATTLIST column value-set CDATA #IMPLIED>

<!-- 校验函数 !-->
<!ATTLIST column validator CDATA #IMPLIED>

<!-- 字段描述 !-->
<!ATTLIST column description CDATA #IMPLIED>


<!-- 主键信息 !-->
<!ELEMENT primary-key (description?)>

<!-- 主键名称 !-->
<!ATTLIST primary-key name CDATA #REQUIRED>

<!-- 字段列表 !-->
<!ATTLIST primary-key column-list CDATA #REQUIRED>

<!-- 索引信息 !-->
<!ELEMENT index (description?)>

<!-- 索引名称 !-->
<!ATTLIST index name CDATA #REQUIRED>

<!-- 索引类型 !-->
<!ATTLIST index index-type (unique | other) "other">

<!-- cluster标志 !-->
<!ATTLIST index cluster (cluster | other) "other">

<!-- 字段列表 !-->
<!ATTLIST index column-list CDATA #REQUIRED>

<!-- 关联表信息 !-->
<!ELEMENT foreign-key (description?)>

<!-- 关联表名称 !-->
<!ATTLIST foreign-key foreign-table CDATA #REQUIRED>

<!-- 映射类型 !-->
<!ATTLIST foreign-key foreign-type (one-to-one | one-to-many | many-to-one) "one-to-one">

<!-- 删除时操作 !-->
<!ATTLIST foreign-key on-delete ( cascade | setnull | restrict | none ) "none">

<!-- 修改时操作 !-->
<!ATTLIST foreign-key on-update ( cascade | setnull | restrict | none ) "none">

<!-- 字段名称 !-->
<!ATTLIST foreign-key column-names CDATA #REQUIRED>

<!-- 外键名称 !-->
<!ATTLIST foreign-key foreign-names CDATA #REQUIRED>

<!-- 函数定义 !-->
<!-- filter-column : 过滤条件 !-->
<!ELEMENT function (filter-column*, description?)>

<!-- 函数名称 !-->
<!ATTLIST function func-name CDATA #REQUIRED>

<!-- 函数类型 !-->
<!ATTLIST function func-type (
		select | rowset | insert | delete | 
		update | procedure | statistic
	) "select">

<!-- 字段列表 !-->
<!ATTLIST function column-list CDATA #IMPLIED>

<!-- 条件定义 !-->
<!ATTLIST function where-define CDATA #IMPLIED>

<!-- 排序字段列表 !-->
<!ATTLIST function sort-columns CDATA #IMPLIED>

<!-- 统计字段 !-->
<!ATTLIST function group-columns CDATA #IMPLIED>

<!-- 查询返回的记录数量 !-->
<!ATTLIST function max-record CDATA #IMPLIED>

<!-- 过滤条件 !-->
<!ELEMENT filter-column EMPTY>

<!-- 字段名称 !-->
<!ATTLIST filter-column column-name CDATA #REQUIRED>

<!-- 比较方式 !-->
<!ATTLIST filter-column operator (eq | ne | lt | le | gt | ge | between | like | start | end | in) "eq">

<!-- 数据来源 !-->
<!ATTLIST filter-column value-from (input | generate | default) "input">

<!-- 转换函数 !-->
<!ATTLIST filter-column func-name CDATA #IMPLIED>

<!-- 条件数据项 !-->
<!ATTLIST filter-column value-item CDATA #IMPLIED>

<!-- 条件数据项2 !-->
<!ATTLIST filter-column value-item2 CDATA #IMPLIED>

<!-- 空值处理 !-->
<!ATTLIST filter-column empty-flag (null | empty | skip) "skip">

<!-- 缺省值 !-->
<!ATTLIST filter-column default CDATA #IMPLIED>

<!-- 连接的数据库名称 !-->
<!ELEMENT database (#PCDATA)>

<!-- 缺省的表处理配置信息 !-->
<!ELEMENT default-config (#PCDATA)>

<!-- 分类名称 !-->
<!ELEMENT sort-name (#PCDATA)>

<!ELEMENT description (#PCDATA)>

=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/classes/config/dao/sys_etl_dbsource.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "gwssi-database.dtd">
<table>
  <default-config>no</default-config>
  <sort-name>系统表</sort-name>
  <table-info name="sys_etl_dbsource" class-name="com.gwssi.dw.runmgr.etl.dao.SysEtlDbsource" check-flag="false" backup-flag="false">
    <description>数据来源管理</description>
  </table-info>

  <column name="sys_etl_dbsource_id" data-type="varchar" length="32" not-null="true" value-from="generate" func-name="getUUID" description="ID"/>
  <column name="dbsource_name" data-type="varchar" length="32" not-null="false" value-from="input" description="数据来源名称"/>
  <column name="dbsource_lb" data-type="char" length="1" not-null="false" value-from="input" description="数据来源类别"/>
  <column name="db_name" data-type="varchar" length="32" not-null="false" value-from="input" description="数据库名称"/>
  <column name="db_ms" data-type="varchar" length="100" not-null="false" value-from="input" description="数据库描述"/>
  <column name="db_user" data-type="varchar" length="32" not-null="false" value-from="input" description="数据库用户"/>
  <column name="db_password" data-type="varchar" length="32" not-null="false" value-from="input" description="数据库密码"/>
  <column name="db_constr" data-type="varchar" length="32" not-null="false" value-from="input" description="数据库连接串"/>
  <column name="db_lb" data-type="varchar" length="32" not-null="false" empty-is-null="false" unique="false" value-from="input"/>
  <primary-key name="dbsource_pk" column-list="sys_etl_dbsource_id"/>
  <index name="dbsource_pk" index-type="unique" cluster="other" column-list="sys_etl_dbsource_id"/>
  <function func-name="select sys_etl_dbsource list" func-type="rowset" column-list="db_lb,dbsource_name,dbsource_lb,db_name,db_ms,db_user,db_password,db_constr,sys_etl_dbsource_id" max-record="10">
    <filter-column column-name="dbsource_lb" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="db_name" operator="like" value-from="input" empty-flag="skip"/>
    <description>多记录查询</description>
  </function>

  <function func-name="select one sys_etl_dbsource" func-type="select" column-list="sys_etl_dbsource_id,dbsource_name,dbsource_lb,db_name,db_ms,db_user,db_password,db_constr,db_lb">
    <filter-column column-name="sys_etl_dbsource_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>单记录查询</description>
  </function>

  <function func-name="delete one sys_etl_dbsource" func-type="delete">
    <filter-column column-name="sys_etl_dbsource_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>删除记录</description>
  </function>

  <function func-name="update one sys_etl_dbsource" func-type="update" column-list="dbsource_name,dbsource_lb,db_name,db_ms,db_user,db_password,db_constr,db_lb">
    <filter-column column-name="sys_etl_dbsource_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>修改记录</description>
  </function>

  <function func-name="insert one sys_etl_dbsource" func-type="insert" column-list="sys_etl_dbsource_id,dbsource_name,dbsource_lb,db_name,db_ms,db_user,db_password,db_constr,db_lb">
    <description>插入记录</description>
  </function>
</table>

=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/classes/config/dao/xt_dclb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "gwssi-database.dtd">
<table>
  <database>gwssi</database>
  <default-config>no</default-config>
  <sort-name>系统表</sort-name>
  <table-info name="xt_dclb" class-name="cn.gwssi.csdb.xt.dao.XtDclb" check-flag="false" backup-flag="false"/>
  <column name="dm_dclb" data-type="varchar" length="2" not-null="true" value-from="input" description="调查类别代码"/>
  <column name="dclb_mc" data-type="varchar" length="30" not-null="true" value-from="input" description="调查类别名称"/>
  <primary-key name="p_xtkey2" column-list="dm_dclb"/>
  <index name="p_xtkey2" index-type="unique" cluster="cluster" column-list="dm_dclb"/>
  <foreign-key foreign-table="xt_dclb" foreign-type="one-to-many" on-delete="none" on-update="none" column-names="dm_dclb" foreign-names="dm_dclb"/>
  <function func-name="select one xt_dclb" func-type="select" column-list="dm_dclb,dclb_mc">
    <description>单记录查询</description>
  </function>

  <function func-name="select xt_dclb list" func-type="rowset" column-list="dm_dclb,dclb_mc" max-record="10">
    <description>多记录查询</description>
  </function>

  <function func-name="insert one xt_dclb" func-type="insert" column-list="dm_dclb,dclb_mc">
    <description>插入记录</description>
  </function>

  <function func-name="delete one xt_dclb" func-type="delete">
    <description>删除记录</description>
  </function>

  <function func-name="bgqb_codeList" func-type="rowset" column-list="dm_dclb as codevalue,dclb_mc as codename" max-record="-1">
    <description>多记录查询</description>
  </function>
</table>
