=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/classes/config/dao/gwssi-database.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT table (database?, default-config?, sort-name?, table-info, column*, primary-key?, index*, foreign-key*, function*)>

<!-- 表信息定义 !-->
<!-- description:字段描述 !-->
<!ELEMENT table-info (description?)>

<!-- 表名称 !-->
<!ATTLIST table-info name CDATA #REQUIRED>

<!-- 对应表的类名称:缺省为cn.gwssi.app.database.目录.表名称 !-->
<!ATTLIST table-info class-name CDATA #IMPLIED>

<!-- 处理缓存记录的类名称 !-->
<!ATTLIST table-info cache-class CDATA #IMPLIED>

<!-- 复核标志：true=修改需要复核、false=不需要复核 !-->
<!ATTLIST table-info check-flag (true | false) "false">

<!-- 保存历史数据的标志：true=修改需要把原始数据保存到历史表、false=不需要保存到历史表 !-->
<!ATTLIST table-info backup-flag (true | false) "false">

<!-- 数据表检测的周期 !-->
<!ATTLIST table-info check-time CDATA  #IMPLIED>


<!-- 字段定义 !-->
<!-- description:字段描述 !-->
<!ELEMENT column EMPTY>

<!-- 字段名称 !-->
<!ATTLIST column name CDATA #REQUIRED>

<!-- 字段对应的数据项名称 !-->
<!ATTLIST column java-name CDATA #IMPLIED>

<!-- 数据类型 !-->
<!ATTLIST column data-type (
		integer | long | decimal | char | varchar | 
		date | time | timestamp | binary
	) "char" >

<!-- 字段长度 !-->
<!ATTLIST column length CDATA #IMPLIED>

<!-- 小数位长度 !-->
<!ATTLIST column fraction-length CDATA #IMPLIED>

<!-- 字段是否能够空 !-->
<!ATTLIST column not-null (true | false) "false">

<!-- 空内容是否转换成NULL !-->
<!ATTLIST column empty-is-null (true | false) "false">

<!-- 缺省值 !-->
<!ATTLIST column default CDATA #IMPLIED>

<!-- 值是否唯一 !-->
<!ATTLIST column unique (true|false) "false">

<!-- 数据内容的来源 !-->
<!ATTLIST column value-from (input | generate | sequence | autoincrement | UUID) "input">

<!-- 转换函数 !-->
<!ATTLIST column func-name CDATA #IMPLIED>

<!-- 取值范围 !-->
<!ATTLIST column value-set CDATA #IMPLIED>

<!-- 校验函数 !-->
<!ATTLIST column validator CDATA #IMPLIED>

<!-- 字段描述 !-->
<!ATTLIST column description CDATA #IMPLIED>


<!-- 主键信息 !-->
<!ELEMENT primary-key (description?)>

<!-- 主键名称 !-->
<!ATTLIST primary-key name CDATA #REQUIRED>

<!-- 字段列表 !-->
<!ATTLIST primary-key column-list CDATA #REQUIRED>

<!-- 索引信息 !-->
<!ELEMENT index (description?)>

<!-- 索引名称 !-->
<!ATTLIST index name CDATA #REQUIRED>

<!-- 索引类型 !-->
<!ATTLIST index index-type (unique | other) "other">

<!-- cluster标志 !-->
<!ATTLIST index cluster (cluster | other) "other">

<!-- 字段列表 !-->
<!ATTLIST index column-list CDATA #REQUIRED>

<!-- 关联表信息 !-->
<!ELEMENT foreign-key (description?)>

<!-- 关联表名称 !-->
<!ATTLIST foreign-key foreign-table CDATA #REQUIRED>

<!-- 映射类型 !-->
<!ATTLIST foreign-key foreign-type (one-to-one | one-to-many | many-to-one) "one-to-one">

<!-- 删除时操作 !-->
<!ATTLIST foreign-key on-delete ( cascade | setnull | restrict | none ) "none">

<!-- 修改时操作 !-->
<!ATTLIST foreign-key on-update ( cascade | setnull | restrict | none ) "none">

<!-- 字段名称 !-->
<!ATTLIST foreign-key column-names CDATA #REQUIRED>

<!-- 外键名称 !-->
<!ATTLIST foreign-key foreign-names CDATA #REQUIRED>

<!-- 函数定义 !-->
<!-- filter-column : 过滤条件 !-->
<!ELEMENT function (filter-column*, description?)>

<!-- 函数名称 !-->
<!ATTLIST function func-name CDATA #REQUIRED>

<!-- 函数类型 !-->
<!ATTLIST function func-type (
		select | rowset | insert | delete | 
		update | procedure | statistic
	) "select">

<!-- 字段列表 !-->
<!ATTLIST function column-list CDATA #IMPLIED>

<!-- 条件定义 !-->
<!ATTLIST function where-define CDATA #IMPLIED>

<!-- 排序字段列表 !-->
<!ATTLIST function sort-columns CDATA #IMPLIED>

<!-- 统计字段 !-->
<!ATTLIST function group-columns CDATA #IMPLIED>

<!-- 查询返回的记录数量 !-->
<!ATTLIST function max-record CDATA #IMPLIED>

<!-- 过滤条件 !-->
<!ELEMENT filter-column EMPTY>

<!-- 字段名称 !-->
<!ATTLIST filter-column column-name CDATA #REQUIRED>

<!-- 比较方式 !-->
<!ATTLIST filter-column operator (eq | ne | lt | le | gt | ge | between | like | start | end | in) "eq">

<!-- 数据来源 !-->
<!ATTLIST filter-column value-from (input | generate | default) "input">

<!-- 转换函数 !-->
<!ATTLIST filter-column func-name CDATA #IMPLIED>

<!-- 条件数据项 !-->
<!ATTLIST filter-column value-item CDATA #IMPLIED>

<!-- 条件数据项2 !-->
<!ATTLIST filter-column value-item2 CDATA #IMPLIED>

<!-- 空值处理 !-->
<!ATTLIST filter-column empty-flag (null | empty | skip) "skip">

<!-- 缺省值 !-->
<!ATTLIST filter-column default CDATA #IMPLIED>

<!-- 连接的数据库名称 !-->
<!ELEMENT database (#PCDATA)>

<!-- 缺省的表处理配置信息 !-->
<!ELEMENT default-config (#PCDATA)>

<!-- 分类名称 !-->
<!ELEMENT sort-name (#PCDATA)>

<!ELEMENT description (#PCDATA)>

=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/classes/config/dao/sys_column_semantic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "gwssi-database.dtd">
<table>
  <database>gwssi</database>
  <default-config>no</default-config>
  <sort-name>系统管理</sort-name>
  <table-info name="sys_column_semantic" class-name="com.gwssi.dw.metadata.datadict.dao.SysColumnSemantic" check-flag="false" backup-flag="false">
    <description>业务表字段语义</description>
  </table-info>

  <column name="table_no" data-type="varchar" length="32" not-null="true" unique="false" value-from="input" description="业务表编码"/>
  <column name="column_no" data-type="varchar" length="32" not-null="true" unique="true" value-from="generate" func-name="getUUID" description="业务字段编码"/>
  <column name="column_name" data-type="varchar" length="60" not-null="true" value-from="input" description="业务字段名"/>
  <column name="column_name_cn" data-type="varchar" length="100" not-null="true" value-from="input" description="业务字段中文名"/>
  <column name="column_order" data-type="integer" length="10" not-null="false" value-from="input" description="检索顺序"/>
  <column name="edit_type" data-type="char" length="2" not-null="true" value-from="input" description="编辑类型"/>
  <column name="edit_content" data-type="varchar" length="100" not-null="false" value-from="input" description="编辑内容"/>
  <column name="demo" data-type="varchar" length="100" not-null="false" value-from="input" description="备注"/>
  <column name="column_byname" data-type="varchar" length="60" not-null="false" empty-is-null="false" unique="false" value-from="input" description="业务字段别名"/>
  <primary-key name="p_key_1" column-list="column_no"/>
  <index name="sql080418142101460" index-type="unique" cluster="other" column-list="column_no"/>
  <index name="idx_ywbzdyy_ywbbm" index-type="other" cluster="other" column-list="table_no,column_order"/>
  <foreign-key foreign-table="sys_table_semantic" foreign-type="one-to-many" on-delete="none" on-update="none" column-names="table_no" foreign-names="table_no"/>
  <function func-name="select one sys_column_semantic" func-type="select" column-list="table_no,column_no,column_name,column_name_cn,column_order,edit_type,edit_content,demo,sys_table_semantic.sys_id,column_byname">
    <filter-column column-name="column_no" operator="eq" value-from="input" empty-flag="skip"/>
    <description>单记录查询</description>
  </function>

  <function func-name="select sys_column_semantic list" func-type="rowset" column-list="table_no,column_no,column_name,column_name_cn,column_order,edit_type,edit_content,demo,sys_table_semantic.sys_id,sys_table_semantic.table_name_cn,sys_table_semantic.table_name" sort-columns="column_name_cn" max-record="10">
    <filter-column column-name="table_no" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="column_name" operator="like" value-from="input" empty-flag="skip"/>
    <filter-column column-name="column_name_cn" operator="like" value-from="input" empty-flag="skip"/>
    <filter-column column-name="sys_table_semantic.sys_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>多记录查询</description>
  </function>

  <function func-name="insert one sys_column_semantic" func-type="insert" column-list="table_no,column_no,column_name,column_name_cn,column_order,edit_type,edit_content,demo,column_byname">
    <description>插入记录</description>
  </function>

  <function func-name="delete one sys_column_semantic" func-type="delete">
    <description>删除记录</description>
  </function>

  <function func-name="update one sys_column_semantic" func-type="update" column-list="table_no,column_name,column_name_cn,column_order,edit_type,edit_content,demo,column_byname">
    <description>修改记录</description>
  </function>
</table>

=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/classes/config/dao/res_collect_table.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "gwssi-database.dtd">
<table>
  <database>gwssi</database>
  <default-config>no</default-config>
  <sort-name>资源管理</sort-name>
  <table-info name="res_collect_table" class-name="com.gwssi.resource.collect.dao.ResCollectTable" check-flag="false" backup-flag="false">
    <description>采集数据表信息表</description>
  </table-info>

  <column name="collect_table_id" data-type="varchar" length="32" not-null="true" value-from="input" description="采集数据表ID"/>
  <column name="service_targets_id" data-type="varchar" length="32" not-null="false" value-from="input" description="服务对象ID"/>
  <column name="table_name_en" data-type="varchar" length="100" not-null="false" value-from="input" description="表名称"/>
  <column name="table_name_cn" data-type="varchar" length="100" not-null="false" value-from="input" description="表中文名称"/>
  <column name="table_type" data-type="varchar" length="20" not-null="false" value-from="input" description="表类型"/>
   <column name="cj_ly" data-type="varchar" length="20" not-null="false" value-from="input" description="采集来源"/>
    <column name="if_creat" data-type="varchar" length="1" not-null="false" value-from="input" description="采集库是否生成采集表"/>
  <column name="table_desc" data-type="varchar" length="2000" not-null="false" value-from="input" description="表描述"/>
  <column name="table_status" data-type="varchar" length="20" not-null="false" value-from="input" description="表状态"/>
  <column name="is_markup" data-type="varchar" length="1" not-null="false" value-from="input" description="有效标记"/>
  <column name="creator_id" data-type="varchar" length="32" not-null="false" value-from="input" description="创建人ID"/>
  <column name="created_time" data-type="varchar" length="19" not-null="false" value-from="input" description="创建时间"/>
  <column name="last_modify_id" data-type="varchar" length="32" not-null="false" value-from="input" description="最后修改人ID"/>
  <column name="last_modify_time" data-type="varchar" length="19" not-null="false" value-from="input" description="最后修改时间"/>
  <column name="fj_fk" data-type="varchar" length="2000" not-null="false" value-from="input" description="附件id"/>
  <column name="fjmc" data-type="varchar" length="2000" not-null="false" value-from="input" description="附件名称"/>
  <primary-key name="pk_res_collect_table" column-list="collect_table_id"/>
  <index name="pk_res_collect_table" index-type="unique" cluster="cluster" column-list="collect_table_id"/>
  <function func-name="select one res_collect_table" func-type="select" column-list="collect_table_id,service_targets_id,table_name_en,table_name_cn,table_type,table_desc,table_status,is_markup,creator_id,created_time,last_modify_id,last_modify_time,cj_ly,if_creat" sort-columns="created_time desc">
    <filter-column column-name="collect_table_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>单记录查询</description>
  </function>

  <function func-name="select res_collect_table list" func-type="rowset" column-list="collect_table_id,service_targets_id,table_name_en,table_name_cn,table_type,table_desc,table_status,is_markup,creator_id,created_time,last_modify_id,last_modify_time,cj_ly,if_creat" sort-columns="created_time desc" max-record="10">
    <filter-column column-name="service_targets_id" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="table_type" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="cj_ly" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="if_creat" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="table_name_en" operator="like" value-from="input" empty-flag="skip"/>
    <filter-column column-name="table_name_cn" operator="like" value-from="input" empty-flag="skip"/>
    <description>多记录查询数据表</description>
  </function>

  <function func-name="insert one res_collect_table" func-type="insert" column-list="collect_table_id,service_targets_id,table_name_en,table_name_cn,table_type,table_desc,table_status,is_markup,creator_id,created_time,last_modify_id,last_modify_time,cj_ly,if_creat">
    <description>插入记录</description>
  </function>

  <function func-name="delete one res_collect_table" func-type="delete">
    <filter-column column-name="collect_table_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>删除记录</description>
  </function>

  <function func-name="update one res_collect_table" func-type="update" column-list="service_targets_id,table_name_en,table_name_cn,table_type,table_desc,table_status,last_modify_id,last_modify_time,cj_ly,if_creat">
    <filter-column column-name="collect_table_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>修改记录</description>
  </function>
</table>

=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/classes/config/dao/sys_advanced_query.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "gwssi-database.dtd">
<table>
  <database>gwssi</database>
  <default-config>no</default-config>
  <sort-name>系统管理</sort-name>
  <table-info name="sys_advanced_query" class-name="com.gwssi.share.query.dao.SysAdvancedQuery" check-flag="false" backup-flag="false">
    <description>高级查询</description>
  </table-info>

  <column name="sys_advanced_query_id" data-type="varchar" length="32" not-null="true" value-from="input" description="高级查询编号"/>
  <column name="name" data-type="varchar" length="200" not-null="true" value-from="input" description="高级查询主题名称"/>
  <column name="display_columns" data-type="binary" length="2147483647" not-null="false" value-from="input" description="高级查询关联表编号"/>
  <column name="table_no" data-type="varchar" length="2000" not-null="false" value-from="input" description="数据表连接条件"/>
  <column name="query_sql" data-type="binary" length="2147483647" not-null="false" value-from="input" description="高级查询SQL"/>
  <column name="create_by" data-type="varchar" length="32" not-null="true" value-from="input" description="创建人"/>
  <column name="sys_svr_user_id" data-type="varchar" length="32" not-null="true" value-from="input" description="创建人id"/>
  <column name="create_date" data-type="varchar" length="20" not-null="true" value-from="input" description="创建日期"/>
  <column name="last_exec_date" data-type="varchar" length="20" not-null="false" value-from="input" description="最后执行日期"/>
  <column name="exec_total" data-type="long" length="38" not-null="true" value-from="input" description="执行次数"/>
  <column name="order_col" data-type="integer" length="38" not-null="true" empty-is-null="false" unique="false" value-from="input" description="排序字段"/>
  <column name="display_columns_en_array" data-type="binary" length="2147483647" not-null="false" value-from="input" description="所有显示字段的英文名"/>
  <column name="display_columns_cn_array" data-type="binary" length="2147483647" not-null="false" value-from="input" description="所有显示字段的中文名"/>
  <primary-key name="pk_sys_advanced_query" column-list="sys_advanced_query_id"/>
  <index name="pk_sys_advanced_query" index-type="unique" cluster="cluster" column-list="sys_advanced_query_id"/>
  <function func-name="select one sys_advanced_query" func-type="select" column-list="sys_advanced_query_id,name,table_no,display_columns,query_sql, create_by,sys_svr_user_id, create_date, last_exec_date, exec_total, display_columns_en_array, display_columns_cn_array">
    <filter-column column-name="sys_advanced_query_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>单记录查询</description>
  </function>

  <function func-name="select sys_advanced_query list" func-type="rowset" column-list="sys_advanced_query_id, name, create_by,sys_svr_user_id, create_date, last_exec_date, exec_total" sort-columns="order_col desc" max-record="10">
    <filter-column column-name="name" operator="like" value-from="input" empty-flag="skip"/>
    <filter-column column-name="create_by" operator="like" value-from="input" empty-flag="skip"/>
    <filter-column column-name="sys_svr_user_id" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="create_date" operator="ge" value-from="input" empty-flag="skip"/>
    <filter-column column-name="create_date" operator="le" value-from="input" empty-flag="skip"/>
    <description>多记录查询</description>
  </function>

  <function func-name="insert one sys_advanced_query" func-type="insert" column-list="sys_advanced_query_id, name, display_columns, table_no, create_by,sys_svr_user_id, create_date, exec_total, order_col, query_sql, display_columns_en_array, display_columns_cn_array">
    <description>插入记录</description>
  </function>

  <function func-name="delete one sys_advanced_query" func-type="delete">
    <filter-column column-name="sys_advanced_query_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>删除记录</description>
  </function>

  <function func-name="update one sys_advanced_query" func-type="update" column-list="name, display_columns, table_no, query_sql, display_columns_en_array, display_columns_cn_array">
    <filter-column column-name="sys_advanced_query_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>修改记录</description>
  </function>

  <function func-name="select sys_advanced_query name" func-type="rowset" column-list="sys_advanced_query_id,name">
    <filter-column column-name="name" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="create_by" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="sys_svr_user_id" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="sys_advanced_query_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>根据查询名称查询，用于插入及修改记录是的名称唯一性的校验</description>
  </function>

  <function func-name="update sql sys_advanced_query" func-type="update" column-list="query_sql">
    <filter-column column-name="sys_advanced_query_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>修改记录</description>
  </function>
</table>

=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/classes/config/dao/sys_db_user.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "gwssi-database.dtd">
<table>
  <database>gwssi</database>
  <default-config>no</default-config>
  <sort-name>共享服务</sort-name>
  <table-info name="sys_db_user" class-name="com.gwssi.dw.runmgr.db.dao.SysDbUser" check-flag="true" backup-flag="false">
    <description>数据库共享对象信息表</description>
  </table-info>

  <column name="sys_db_user_id" data-type="varchar" length="32" not-null="true" value-from="generate" func-name="getUUID" description="共享对象ID"/>
  <column name="login_name" data-type="varchar" length="32" not-null="true" value-from="input" description="登录用户名"/>
  <column name="password" data-type="varchar" length="32" not-null="true" value-from="input" description="登录密码"/>
  <column name="create_date" data-type="varchar" length="10" not-null="true" value-from="input" description="创建日期"/>
  <column name="create_by" data-type="varchar" length="32" not-null="true" value-from="input" description="创建人"/>
  <column name="state" data-type="long" length="38" not-null="true" value-from="input" description="状态（启用或停用）"/>
  <column name="user_desc" data-type="varchar" length="1000" not-null="false" value-from="input" description="用户描述"/>
  <column name="user_type" data-type="varchar" length="10" not-null="false" value-from="input" description="用户类型"/>
  <column name="user_name" data-type="varchar" length="32" not-null="true" value-from="input" description="用户名称"/>
  <column name="user_order" data-type="long" length="38" not-null="true" value-from="input" description="用户顺序"/>
  <column name="grant_table" data-type="varchar" length="2000" not-null="false" value-from="input" description="该用户已经被授权的表"/>
  <primary-key name="sys_c009540" column-list="sys_db_user_id"/>
  <index name="sys_c009540" index-type="unique" cluster="cluster" column-list="sys_db_user_id"/>
  <function func-name="select one sys_db_user" func-type="select" column-list="sys_db_user_id,login_name,user_name,password,create_date,create_by,state,user_desc,user_type,grant_table">
    <filter-column column-name="sys_db_user_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>单记录查询</description>
  </function>

  <function func-name="select sys_db_user list" func-type="rowset" column-list="sys_db_user_id,login_name,password,user_name,create_date,create_by,state,user_type,grant_table" sort-columns="user_name" max-record="10">
    <filter-column column-name="login_name" operator="like" value-from="input" empty-flag="skip"/>
    <filter-column column-name="state" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="user_type" operator="eq" value-from="input" empty-flag="skip"/>
    <description>多记录查询</description>
  </function>

  <function func-name="select exist sys_db_user list" func-type="rowset" column-list="sys_db_user_id" max-record="10">
    <filter-column column-name="login_name" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="user_name" operator="eq" value-from="input" empty-flag="skip"/>
    <description>多记录查询</description>
  </function>

  <function func-name="insert one sys_db_user" func-type="insert" column-list="sys_db_user_id,login_name,user_name,password,create_date,create_by,state,user_order,user_type">
    <description>插入记录</description>
  </function>

  <function func-name="delete one sys_db_user" func-type="delete">
    <filter-column column-name="sys_db_user_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>删除记录</description>
  </function>

  <function func-name="update one sys_db_user" func-type="update" column-list="login_name,user_name,state">
    <filter-column column-name="sys_db_user_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>修改记录</description>
  </function>

  <function func-name="update one sys_db_user state" func-type="update" column-list="state">
    <filter-column column-name="sys_db_user_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>修改状态</description>
  </function>

  <function func-name="select one sys_db_user_name" func-type="rowset" column-list="sys_db_user_id">
    <filter-column column-name="login_name" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="user_name" operator="eq" value-from="input" empty-flag="skip"/>
    <description>单记录查询</description>
  </function>

  <function func-name="select one sys_db_user_password" func-type="rowset" column-list="sys_db_user_id">
    <filter-column column-name="sys_db_user_id" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="password" operator="eq" value-from="input" empty-flag="skip"/>
    <description>单记录查询-密码</description>
  </function>

  <function func-name="select user_order sys_db_user" func-type="select" column-list="max(user_order) as user_order">
    <description>单记录查询</description>
  </function>

  <function func-name="reset sys_db_user password" func-type="update" column-list="password">
    <filter-column column-name="sys_db_user_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>修改记录</description>
  </function>
</table>

=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/classes/config/dao/sys_table_semantic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "gwssi-database.dtd">
<table>
  <database>gwssi</database>
  <default-config>no</default-config>
  <sort-name>系统管理</sort-name>
  <table-info name="sys_table_semantic" class-name="com.gwssi.dw.metadata.datadict.dao.SysTableSemantic" check-flag="false" backup-flag="false">
    <description>业务表语义</description>
  </table-info>

  <column name="table_no" data-type="varchar" length="32" not-null="true" unique="true" value-from="generate" func-name="getUUID" description="业务表编码"/>
  <column name="table_name" data-type="varchar" length="60" not-null="true" value-from="input" description="业务表名"/>
  <column name="table_name_cn" data-type="varchar" length="100" not-null="true" value-from="input" description="业务表中文名"/>
  <column name="table_order" data-type="integer" length="10" not-null="false" value-from="input" description="检索顺序"/>
  <column name="demo" data-type="varchar" length="100" not-null="false" value-from="input" description="备注"/>
  <column name="sys_id" data-type="varchar" length="32" not-null="true" unique="true" value-from="input" description="业务系统ID"/>
  <column name="downloadflag" data-type="char" length="1" not-null="false" empty-is-null="false" unique="false" value-from="input" description="是否可下载"/>
  <primary-key name="p_key_1" column-list="table_no"/>
  <index name="sql080418142102090" index-type="unique" cluster="other" column-list="table_no"/>
  <index name="idx_ywbyy_xtbm" index-type="other" cluster="other" column-list="table_order"/>
  <foreign-key foreign-table="sys_system_semantic" foreign-type="many-to-one" on-delete="none" on-update="none" column-names="sys_id" foreign-names="sys_id"/>
  <function func-name="select one sys_table_semantic" func-type="select" column-list="sys_id,table_name,table_name_cn,table_order,demo,table_no,downloadflag">
    <filter-column column-name="table_no" operator="eq" value-from="input" empty-flag="skip"/>
    <description>单记录查询</description>
  </function>

  <function func-name="select sys_table_semantic list" func-type="rowset" column-list="table_no,table_name,table_name_cn,table_order,demo,sys_id,sys_system_semantic.sys_no,downloadflag,sys_system_semantic.sys_name" sort-columns="sys_system_semantic.sys_name,table_name_cn" max-record="10">
    <filter-column column-name="sys_id" operator="eq" value-from="input" empty-flag="skip"/>
    <filter-column column-name="table_name" operator="like" value-from="input" empty-flag="skip"/>
    <filter-column column-name="table_name_cn" operator="like" value-from="input" empty-flag="skip"/>
    <description>多记录查询</description>
  </function>

  <function func-name="insert one sys_table_semantic" func-type="insert" column-list="sys_id,table_no,table_name,table_name_cn,table_order,demo,downloadflag">
    <description>插入记录</description>
  </function>

  <function func-name="delete one sys_table_semantic" func-type="delete">
    <description>删除记录</description>
  </function>

  <function func-name="update one sys_table_semantic" func-type="update" column-list="table_name,table_name_cn,table_order,demo,sys_id,downloadflag">
    <filter-column column-name="table_no" operator="eq" value-from="input" empty-flag="skip"/>
    <description>修改记录</description>
  </function>

  <function func-name="业务系统表代码对照表" func-type="rowset" column-list="table_name_cn as codename, table_no as codevalue" sort-columns="sys_system_semantic.sys_name,table_name_cn" max-record="-1">
    <description>多记录查询</description>
  </function>

  <function func-name="select sys_table_semantic list by system" func-type="rowset" column-list="sys_id,table_no,table_name,table_name_cn,table_order,demo,downloadflag" max-record="10">
    <filter-column column-name="sys_id" operator="eq" value-from="input" empty-flag="skip"/>
    <description>多记录查询</description>
  </function>
</table>
