=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/struts/gwssi-struts.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT struts-config (menu-name, menu-path?, description?, form-beans?, action-mappings?, resource?)>
<!ELEMENT menu-name (#PCDATA)>
<!ELEMENT menu-path (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT form-beans (form-bean+)>
<!ELEMENT action-mappings (action+)>

<!ELEMENT form-bean (description?, set-property*, form-property*)>
<!ATTLIST form-bean
	name CDATA #REQUIRED
>
<!ELEMENT action (description?, step*, forward*)>

<!-- input 输入的页面名称 !-->
<!ATTLIST action	input CDATA #REQUIRED>
<!-- name 对应的form名称 !-->
<!ATTLIST action	name CDATA #REQUIRED>
<!-- txn-code 功能对应的交易码 !-->
<!ATTLIST action	txn-code CDATA #REQUIRED>
<!-- check-type 是否需要检查交易的权限：public、login、check、system !-->
<!ATTLIST action	check-type (public | login | check | system) "check">
<!-- container 交易容器的名称 !-->
<!ATTLIST action	container CDATA #IMPLIED>
<!-- 业务类型：实时交易、批量交易、异步交易、限制交易、低优先级交易、系统交易 !-->
<!ATTLIST action	txn-type (transaction | batch | async | restricted | system) "transaction">
<!-- 是否允许重复提交 !-->
<!ATTLIST action	re-entry (true | false) "false">
<!-- 是否记录日志 !-->
<!ATTLIST action	log-flag (true | false) "true">
<!-- 交易对应的流程编号 !-->
<!ATTLIST action	flow-id CDATA #IMPLIED>
<!-- 重定向的页面地址 !-->
<!ATTLIST action	domain-name CDATA #IMPLIED>

<!ELEMENT form-property EMPTY>

<!-- prefix 名称的前缀 !-->
<!ATTLIST form-property	prefix CDATA #IMPLIED>
<!-- name 变量的名称 !-->
<!ATTLIST form-property	name CDATA #REQUIRED>
<!-- type 变量的类型 !-->
<!ATTLIST form-property	type (string | long | int | date | double | float | file | object) "string">
<!-- size 变量的长度 !-->
<!ATTLIST form-property	size CDATA #IMPLIED>
<!-- cannull 变量是否能够为空值，缺省能够为空 !-->
<!ATTLIST form-property	cannull (true | false) "true">
<!-- 数据格式 !-->
<!ATTLIST form-property	data-format CDATA #IMPLIED>
<!-- valid-rule 数据有效性规则 !-->
<!ATTLIST form-property	valid-rule CDATA #IMPLIED>
<!-- init-value 变量的缺省值 !-->
<!ATTLIST form-property	init-value CDATA #IMPLIED>
<!-- input-type 变量的输入输出域类型 !-->
<!ATTLIST form-property	input-type CDATA #IMPLIED>
<!-- param-name 变量的有效值信息 !-->
<!ATTLIST form-property	param-name CDATA #IMPLIED>
<!-- 字段描述 !-->
<!ATTLIST form-property	description CDATA #IMPLIED>


<!ELEMENT step (init-value*, next-step*)>
<!-- 序号 !-->
<!ATTLIST step	index CDATA #REQUIRED>
<!-- bean-name 业务组件的名称 !-->
<!ATTLIST step	bean-name CDATA #REQUIRED>
<!-- func-name 方法的名称 !-->
<!ATTLIST step	func-name CDATA #IMPLIED>
<!-- 输入节点名称 !-->
<!ATTLIST step	input-node CDATA #IMPLIED>
<!-- 输出节点名称 !-->
<!ATTLIST step	output-node CDATA #IMPLIED>
<!-- VO名称 !-->
<!ATTLIST step	vo-bean CDATA #IMPLIED>
<!-- 描述信息 !-->
<!ATTLIST step	description CDATA #IMPLIED>


<!-- 下一步信息 !-->
<!ELEMENT next-step EMPTY>
<!ATTLIST next-step	error-code CDATA #IMPLIED>
<!ATTLIST next-step	next-index CDATA #REQUIRED>


<!ELEMENT set-property EMPTY>
<!ATTLIST set-property
	property CDATA #REQUIRED
	value CDATA #REQUIRED
>

<!ELEMENT init-value EMPTY>
<!ATTLIST init-value
	property CDATA #REQUIRED
	value CDATA #REQUIRED
>

<!ELEMENT forward EMPTY>
<!ATTLIST forward
	name CDATA #IMPLIED
	error-code CDATA #IMPLIED
	path CDATA #REQUIRED
	redirect (true | false) "false"
>

<!-- 功能的相关文件 -->
<!ELEMENT resource (resource-file*)>
<!ELEMENT resource-file EMPTY>
<!ATTLIST resource-file type        CDATA #REQUIRED>
<!ATTLIST resource-file file-name   CDATA #REQUIRED>
<!ATTLIST resource-file description CDATA #IMPLIED>

=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/struts/share_srv_scheduling.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struts-config SYSTEM "gwssi-struts.dtd">
<struts-config>
  <menu-name>共享任务调度</menu-name>
  <menu-path>/page/share/ftp/scheduling/</menu-path>
  <description>共享任务调度</description>
  <form-beans>
    <form-bean name="ShareSrvSchedulingRowsetForm">
      <description>多记录查询</description>
      <form-property prefix="record" name="srv_scheduling_id" type="string" size="32" cannull="false" description="任务调度ID"/>
      <form-property prefix="record" name="service_id" type="string" size="32" cannull="true" description="服务ID"/>
      <form-property prefix="record" name="service_no" type="string" size="20" cannull="true" description="服务编号"/>
      <form-property prefix="record" name="service_name" type="string" size="100" cannull="true" description="任务名称"/>
      <form-property prefix="record" name="job_class_name" type="string" size="100" cannull="true" description="触发调用的类名"/>
      <form-property prefix="record" name="scheduling_type" type="string" size="2" cannull="true" description="计划任务类型"/>
      <form-property prefix="record" name="scheduling_day" type="string" size="2" cannull="true" description="计划任务日期"/>
      <form-property prefix="record" name="start_time" type="string" size="10" cannull="true" description="计划任务开始时间"/>
      <form-property prefix="record" name="end_time" type="string" size="10" cannull="true" description="计划任务结束时间"/>
      <form-property prefix="record" name="scheduling_count" type="string" size="4" cannull="true" description="计划任务执行次数"/>
      <form-property prefix="record" name="interval_time" type="string" size="3" cannull="true" description="每次间隔时间"/>
      <form-property prefix="record" name="scheduling_week" type="string" size="100" cannull="true" description="计划任务周天"/>
      <form-property prefix="record" name="scheduling_day1" type="string" size="500" cannull="true" description="计划任务周期中文"/>
      <form-property prefix="record" name="task_expression" type="string" size="200" cannull="true" description="表达式"/>
      <form-property prefix="record" name="is_markup" type="string" size="1" cannull="true" description="代码表 有效 无效"/>
      <form-property prefix="record" name="creator_id" type="string" size="32" cannull="true" description="创建人ID"/>
      <form-property prefix="record" name="created_time" type="string" size="19" cannull="true" description="创建时间"/>
      <form-property prefix="record" name="last_modify_id" type="string" size="32" cannull="true" description="最后修改人ID"/>
      <form-property prefix="record" name="last_modify_time" type="string" size="19" cannull="true" description="最后修改时间"/>
    </form-bean>

    <form-bean name="ShareSrvSchedulingUpdateForm">
      <description>单记录处理：查询、修改、增加</description>
      <form-property prefix="primary-key" name="srv_scheduling_id" type="string" size="32" cannull="false" description="任务调度ID"/>
      <form-property prefix="record" name="srv_scheduling_id" type="string" size="32" cannull="false" description="任务调度ID"/>
      <form-property prefix="record" name="service_id" type="string" size="32" cannull="true" description="服务ID"/>
      <form-property prefix="record" name="service_no" type="string" size="20" cannull="true" description="服务编号"/>
      <form-property prefix="record" name="service_name" type="string" size="100" cannull="true" description="任务名称"/>
      <form-property prefix="record" name="job_class_name" type="string" size="100" cannull="true" description="触发调用的类名"/>
      <form-property prefix="record" name="scheduling_type" type="string" size="2" cannull="true" description="计划任务类型"/>
      <form-property prefix="record" name="scheduling_day" type="string" size="2" cannull="true" description="计划任务日期"/>
      <form-property prefix="record" name="start_time" type="string" size="10" cannull="true" description="计划任务开始时间"/>
      <form-property prefix="record" name="end_time" type="string" size="10" cannull="true" description="计划任务结束时间"/>
      <form-property prefix="record" name="scheduling_count" type="string" size="4" cannull="true" description="计划任务执行次数"/>
      <form-property prefix="record" name="interval_time" type="string" size="3" cannull="true" description="每次间隔时间"/>
      <form-property prefix="record" name="scheduling_week" type="string" size="100" cannull="true" description="计划任务周天"/>
      <form-property prefix="record" name="scheduling_day1" type="string" size="500" cannull="true" description="计划任务周期中文"/>
      <form-property prefix="record" name="task_expression" type="string" size="200" cannull="true" description="表达式"/>
      <form-property prefix="record" name="is_markup" type="string" size="1" cannull="true" description="代码表 有效 无效"/>
      <form-property prefix="record" name="creator_id" type="string" size="32" cannull="true" description="创建人ID"/>
      <form-property prefix="record" name="created_time" type="string" size="19" cannull="true" description="创建时间"/>
      <form-property prefix="record" name="last_modify_id" type="string" size="32" cannull="true" description="最后修改人ID"/>
      <form-property prefix="record" name="last_modify_time" type="string" size="19" cannull="true" description="最后修改时间"/>
    </form-bean>

    <form-bean name="ShareSrvSchedulingDeleteForm">
      <description>多记录和单记录删除</description>
      <form-property prefix="primary-key" name="srv_scheduling_id" type="string" size="32" cannull="false" description="任务调度ID"/>
    </form-bean>
  </form-beans>

  <action-mappings>
    <action input="query-share_srv_scheduling.jsp" name="ShareSrvSchedulingRowsetForm" txn-code="40400001" check-type="check" container="default" txn-type="transaction" re-entry="true" log-flag="true">
      <description>查询共享调度列表</description>
      <step index="10" bean-name="com.gwssi.share.ftp.txn.TxnShareSrvScheduling" func-name="txn40400001" input-node="select-key" output-node="record" description="查询共享调度列表"/>
      <forward error-code="success" path="query-share_srv_scheduling.jsp"/>
      <forward error-code="failure" path="query-share_srv_scheduling.jsp"/>
    </action>

    <action input="update-share_srv_scheduling.jsp" name="ShareSrvSchedulingUpdateForm" txn-code="40400002" check-type="check" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>修改共享调度信息</description>
      <step index="10" bean-name="com.gwssi.share.ftp.txn.TxnShareSrvScheduling" func-name="txn40400002" input-node="record" description="修改共享调度信息"/>
      <forward error-code="success" path="update-share_srv_scheduling.jsp"/>
      <forward error-code="failure" path="update-share_srv_scheduling.jsp"/>
    </action>

    <action input="insert-share_srv_scheduling.jsp" name="ShareSrvSchedulingUpdateForm" txn-code="40400003" check-type="public" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>增加共享调度信息</description>
      <step index="10" bean-name="com.gwssi.share.ftp.txn.TxnShareSrvScheduling" func-name="txn40400003" input-node="record" description="增加共享调度信息"/>
      <forward error-code="success" path="insert-share_srv_scheduling.jsp"/>
      <forward error-code="failure" path="insert-share_srv_scheduling.jsp"/>
    </action>

    <action input="query-share_srv_scheduling.jsp" name="ShareSrvSchedulingUpdateForm" txn-code="40400004" check-type="check" container="default" txn-type="transaction" re-entry="true" log-flag="true">
      <description>查询共享调度用于修改</description>
      <step index="10" bean-name="com.gwssi.share.ftp.txn.TxnShareSrvScheduling" func-name="txn40400004" input-node="primary-key" output-node="record" description="查询共享调度用于修改"/>
      <forward error-code="success" path="update-share_srv_scheduling.jsp"/>
      <forward error-code="failure" path="update-share_srv_scheduling.jsp"/>
    </action>

    <action input="query-share_srv_scheduling.jsp" name="ShareSrvSchedulingDeleteForm" txn-code="40400005" check-type="check" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>删除共享调度信息</description>
      <step index="10" bean-name="com.gwssi.share.ftp.txn.TxnShareSrvScheduling" func-name="txn40400005" input-node="primary-key" description="删除共享调度信息"/>
      <forward error-code="success" path="/script/deletesuccess.jsp"/>
      <forward error-code="failure" path="/script/deletefailure.jsp"/>
    </action>
  </action-mappings>

  <resource>
    <resource-file type="model" file-name="/WEB-INF/resource/jsp-frame/menu-share_srv_scheduling.xml" description="模板文件"/>
    <resource-file type="jsp" file-name="/page/share/ftp/scheduling/query-share_srv_scheduling.jsp" description="查询共享调度列表"/>
    <resource-file type="jsp" file-name="/page/share/ftp/scheduling/insert-share_srv_scheduling.jsp" description="增加共享调度信息"/>
    <resource-file type="jsp" file-name="/page/share/ftp/scheduling/update-share_srv_scheduling.jsp" description="修改共享调度信息"/>
    <resource-file type="vo-bean" file-name="com.gwssi.share.ftp.vo.ShareSrvSchedulingContext" description="应用对应的数据上下文对象"/>
    <resource-file type="vo-bean" file-name="com.gwssi.share.ftp.vo.VoShareSrvScheduling" description="数据表字段对应的VO对象"/>
    <resource-file type="vo-bean" file-name="com.gwssi.share.ftp.vo.VoShareSrvSchedulingSelectKey" description="查询条件对应的VO对象"/>
    <resource-file type="vo-bean" file-name="com.gwssi.share.ftp.vo.VoShareSrvSchedulingPrimaryKey" description="数据库主键对应的VO对象"/>
  </resource>
</struts-config>
