=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/struts/gwssi-struts.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT struts-config (menu-name, menu-path?, description?, form-beans?, action-mappings?, resource?)>
<!ELEMENT menu-name (#PCDATA)>
<!ELEMENT menu-path (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT form-beans (form-bean+)>
<!ELEMENT action-mappings (action+)>

<!ELEMENT form-bean (description?, set-property*, form-property*)>
<!ATTLIST form-bean
	name CDATA #REQUIRED
>
<!ELEMENT action (description?, step*, forward*)>

<!-- input 输入的页面名称 !-->
<!ATTLIST action	input CDATA #REQUIRED>
<!-- name 对应的form名称 !-->
<!ATTLIST action	name CDATA #REQUIRED>
<!-- txn-code 功能对应的交易码 !-->
<!ATTLIST action	txn-code CDATA #REQUIRED>
<!-- check-type 是否需要检查交易的权限：public、login、check、system !-->
<!ATTLIST action	check-type (public | login | check | system) "check">
<!-- container 交易容器的名称 !-->
<!ATTLIST action	container CDATA #IMPLIED>
<!-- 业务类型：实时交易、批量交易、异步交易、限制交易、低优先级交易、系统交易 !-->
<!ATTLIST action	txn-type (transaction | batch | async | restricted | system) "transaction">
<!-- 是否允许重复提交 !-->
<!ATTLIST action	re-entry (true | false) "false">
<!-- 是否记录日志 !-->
<!ATTLIST action	log-flag (true | false) "true">
<!-- 交易对应的流程编号 !-->
<!ATTLIST action	flow-id CDATA #IMPLIED>
<!-- 重定向的页面地址 !-->
<!ATTLIST action	domain-name CDATA #IMPLIED>

<!ELEMENT form-property EMPTY>

<!-- prefix 名称的前缀 !-->
<!ATTLIST form-property	prefix CDATA #IMPLIED>
<!-- name 变量的名称 !-->
<!ATTLIST form-property	name CDATA #REQUIRED>
<!-- type 变量的类型 !-->
<!ATTLIST form-property	type (string | long | int | date | double | float | file | object) "string">
<!-- size 变量的长度 !-->
<!ATTLIST form-property	size CDATA #IMPLIED>
<!-- cannull 变量是否能够为空值，缺省能够为空 !-->
<!ATTLIST form-property	cannull (true | false) "true">
<!-- 数据格式 !-->
<!ATTLIST form-property	data-format CDATA #IMPLIED>
<!-- valid-rule 数据有效性规则 !-->
<!ATTLIST form-property	valid-rule CDATA #IMPLIED>
<!-- init-value 变量的缺省值 !-->
<!ATTLIST form-property	init-value CDATA #IMPLIED>
<!-- input-type 变量的输入输出域类型 !-->
<!ATTLIST form-property	input-type CDATA #IMPLIED>
<!-- param-name 变量的有效值信息 !-->
<!ATTLIST form-property	param-name CDATA #IMPLIED>
<!-- 字段描述 !-->
<!ATTLIST form-property	description CDATA #IMPLIED>


<!ELEMENT step (init-value*, next-step*)>
<!-- 序号 !-->
<!ATTLIST step	index CDATA #REQUIRED>
<!-- bean-name 业务组件的名称 !-->
<!ATTLIST step	bean-name CDATA #REQUIRED>
<!-- func-name 方法的名称 !-->
<!ATTLIST step	func-name CDATA #IMPLIED>
<!-- 输入节点名称 !-->
<!ATTLIST step	input-node CDATA #IMPLIED>
<!-- 输出节点名称 !-->
<!ATTLIST step	output-node CDATA #IMPLIED>
<!-- VO名称 !-->
<!ATTLIST step	vo-bean CDATA #IMPLIED>
<!-- 描述信息 !-->
<!ATTLIST step	description CDATA #IMPLIED>


<!-- 下一步信息 !-->
<!ELEMENT next-step EMPTY>
<!ATTLIST next-step	error-code CDATA #IMPLIED>
<!ATTLIST next-step	next-index CDATA #REQUIRED>


<!ELEMENT set-property EMPTY>
<!ATTLIST set-property
	property CDATA #REQUIRED
	value CDATA #REQUIRED
>

<!ELEMENT init-value EMPTY>
<!ATTLIST init-value
	property CDATA #REQUIRED
	value CDATA #REQUIRED
>

<!ELEMENT forward EMPTY>
<!ATTLIST forward
	name CDATA #IMPLIED
	error-code CDATA #IMPLIED
	path CDATA #REQUIRED
	redirect (true | false) "false"
>

<!-- 功能的相关文件 -->
<!ELEMENT resource (resource-file*)>
<!ELEMENT resource-file EMPTY>
<!ATTLIST resource-file type        CDATA #REQUIRED>
<!ATTLIST resource-file file-name   CDATA #REQUIRED>
<!ATTLIST resource-file description CDATA #IMPLIED>

=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/struts/jgyhxz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struts-config SYSTEM "gwssi-struts.dtd">
<struts-config>
  <menu-name>选择机构用户</menu-name>
  <menu-path>/page/sysmgr/choice/orguserchoice/</menu-path>
  <description>选择用户</description>
  <form-beans>
    <form-bean name="JgyhxzRowsetForm">
      <description>多记录查询</description>
      <form-property prefix="select-key" name="jgid_pk" type="string" size="32" cannull="false" description="机构ID"/>
      <form-property prefix="select-key" name="sjjgid_fk" type="string" size="32" cannull="true" description="上级机构ID"/>
      <form-property prefix="select-key" name="jgmc" type="string" size="60" cannull="false" description="机构名称"/>
      <form-property prefix="input-data" name="jgid_pk" type="string" size="32" cannull="false" description="机构ID"/>
      <form-property prefix="input-data" name="jgid_fk" type="string" size="32" cannull="false" description="机构ID"/>
    </form-bean>
  </form-beans>

  <action-mappings>
    <action input="main.jsp" name="JgyhxzRowsetForm" txn-code="808002" check-type="public" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <step index="808002" bean-name="com.gwssi.sysmgr.choice.TxnJgyhxz" func-name="txn808002" input-node="input-data" output-node="select-key" description="机构用户选择"/>
      <forward error-code="success" path="tree.jsp" redirect="false"/>
      <forward error-code="failure" path="tree.jsp" redirect="false"/>
    </action>
  </action-mappings>
</struts-config>

=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/struts/res_business_topics.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struts-config SYSTEM "gwssi-struts.dtd">
<struts-config>
  <menu-name>业务主题表</menu-name>
  <menu-path>/page/resource/share/</menu-path>
  <description>业务主题表</description>
  <form-beans>
    <form-bean name="ResBusinessTopicsRowsetForm">
      <description>多记录查询</description>
      <form-property prefix="record" name="business_topics_id" type="string" size="32" cannull="false" description="业务主题ID"/>
      <form-property prefix="record" name="service_targets_id" type="string" size="32" cannull="true" description="服务对象ID"/>
      <form-property prefix="record" name="topics_name" type="string" size="100" cannull="true" description="主题名称"/>
      <form-property prefix="record" name="topics_no" type="string" size="10" cannull="true" description="主题编号"/>
      <form-property prefix="record" name="topics_desc" type="string" size="2000" cannull="true" description="主题描述"/>
      <form-property prefix="record" name="show_order" type="long" cannull="true" description="显示顺序"/>
    </form-bean>

    <form-bean name="ResBusinessTopicsUpdateForm">
      <description>单记录处理：查询、修改、增加</description>
      <form-property prefix="primary-key" name="business_topics_id" type="string" size="32" cannull="false" description="业务主题ID"/>
      <form-property prefix="record" name="business_topics_id" type="string" size="32" cannull="false" description="业务主题ID"/>
      <form-property prefix="record" name="service_targets_id" type="string" size="32" cannull="true" description="服务对象ID"/>
      <form-property prefix="record" name="topics_name" type="string" size="100" cannull="true" description="主题名称"/>
      <form-property prefix="record" name="topics_no" type="string" size="10" cannull="true" description="主题编号"/>
      <form-property prefix="record" name="topics_desc" type="string" size="2000" cannull="true" description="主题描述"/>
      <form-property prefix="record" name="show_order" type="long" cannull="true" description="显示顺序"/>
    </form-bean>

    <form-bean name="ResBusinessTopicsDeleteForm">
      <description>多记录和单记录删除</description>
      <form-property prefix="primary-key" name="business_topics_id" type="string" size="32" cannull="false" description="业务主题ID"/>
    </form-bean>
  </form-beans>

  <action-mappings>
    <action input="query-res_business_topics.jsp" name="ResBusinessTopicsRowsetForm" txn-code="203011" check-type="check" container="default" txn-type="transaction" re-entry="true" log-flag="true">
      <description>查询共享主题列表</description>
      <step index="10" bean-name="com.gwssi.resource.share.txn.TxnResBusinessTopics" func-name="txn203011" input-node="select-key" output-node="record" description="查询共享主题列表"/>
      <forward error-code="success" path="query-res_business_topics.jsp"/>
      <forward error-code="failure" path="query-res_business_topics.jsp"/>
    </action>

    <action input="update-res_business_topics.jsp" name="ResBusinessTopicsUpdateForm" txn-code="203012" check-type="check" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>修改共享主题信息</description>
      <step index="10" bean-name="com.gwssi.resource.share.txn.TxnResBusinessTopics" func-name="txn203012" input-node="record" description="修改共享主题信息"/>
      <forward error-code="success" path="update-res_business_topics.jsp"/>
      <forward error-code="failure" path="update-res_business_topics.jsp"/>
    </action>

    <action input="insert-res_business_topics.jsp" name="ResBusinessTopicsUpdateForm" txn-code="203013" check-type="check" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>增加共享主题信息</description>
      <step index="10" bean-name="com.gwssi.resource.share.txn.TxnResBusinessTopics" func-name="txn203013" input-node="record" description="增加共享主题信息"/>
      <forward error-code="success" path="insert-res_business_topics.jsp"/>
      <forward error-code="failure" path="insert-res_business_topics.jsp"/>
    </action>

    <action input="query-res_business_topics.jsp" name="ResBusinessTopicsUpdateForm" txn-code="203014" check-type="check" container="default" txn-type="transaction" re-entry="true" log-flag="true">
      <description>查询共享主题用于修改</description>
      <step index="10" bean-name="com.gwssi.resource.share.txn.TxnResBusinessTopics" func-name="txn203014" input-node="primary-key" output-node="record" description="查询共享主题用于修改"/>
      <forward error-code="success" path="update-res_business_topics.jsp"/>
      <forward error-code="failure" path="update-res_business_topics.jsp"/>
    </action>

    <action input="query-res_business_topics.jsp" name="ResBusinessTopicsDeleteForm" txn-code="203015" check-type="check" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>删除共享主题信息</description>
      <step index="10" bean-name="com.gwssi.resource.share.txn.TxnResBusinessTopics" func-name="txn203015" input-node="primary-key" description="删除共享主题信息"/>
      <forward error-code="success" path="/script/deletesuccess.jsp"/>
      <forward error-code="failure" path="/script/deletefailure.jsp"/>
    </action>
  </action-mappings>

  <resource>
    <resource-file type="model" file-name="/WEB-INF/resource/jsp-frame/menu-res_business_topics.xml" description="模板文件"/>
    <resource-file type="jsp" file-name="/page/resource/share/query-res_business_topics.jsp" description="查询共享主题列表"/>
    <resource-file type="jsp" file-name="/page/resource/share/insert-res_business_topics.jsp" description="增加共享主题信息"/>
    <resource-file type="jsp" file-name="/page/resource/share/update-res_business_topics.jsp" description="修改共享主题信息"/>
    <resource-file type="vo-bean" file-name="com.gwssi.resource.share.vo.ResBusinessTopicsContext" description="应用对应的数据上下文对象"/>
    <resource-file type="vo-bean" file-name="com.gwssi.resource.share.vo.VoResBusinessTopics" description="数据表字段对应的VO对象"/>
    <resource-file type="vo-bean" file-name="com.gwssi.resource.share.vo.VoResBusinessTopicsSelectKey" description="查询条件对应的VO对象"/>
    <resource-file type="vo-bean" file-name="com.gwssi.resource.share.vo.VoResBusinessTopicsPrimaryKey" description="数据库主键对应的VO对象"/>
  </resource>
</struts-config>

=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/struts/view_func_name_log.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struts-config SYSTEM "gwssi-struts.dtd">
<struts-config>
  <menu-name>功能大小类对应表</menu-name>
  <menu-path>/page/log/</menu-path>
  <description>功能大小类对应表</description>
  <form-beans>
    <form-bean name="ViewFuncNameLogRowsetForm">
      <description>多记录查询</description>
      <form-property prefix="record" name="first_func_name" type="string" size="8" cannull="true" description="功能大类"/>
      <form-property prefix="record" name="second_func_name" type="string" size="200" cannull="true" description="功能小类"/>
    </form-bean>

    <form-bean name="ViewFuncNameLogUpdateForm">
      <description>单记录处理：查询、修改、增加</description>
      <form-property prefix="record" name="first_func_name" type="string" size="8" cannull="true" description="功能大类"/>
      <form-property prefix="record" name="second_func_name" type="string" size="200" cannull="true" description="功能小类"/>
    </form-bean>

    <form-bean name="ViewFuncNameLogDeleteForm">
      <description>多记录和单记录删除</description>
    </form-bean>
  </form-beans>

  <action-mappings>
    <action input="query-view_func_name_log.jsp" name="ViewFuncNameLogRowsetForm" txn-code="620100401" check-type="public" container="default" txn-type="transaction" re-entry="true" log-flag="true">
      <description>查询功能大小类对应列表</description>
      <step index="10" bean-name="cn.gwssi.dw.rd.log.txn.TxnViewFuncNameLog" func-name="txn620100401" input-node="select-key" output-node="record" description="查询功能大小类对应列表"/>
      <forward error-code="success" path="query-view_func_name_log.jsp"/>
      <forward error-code="failure" path="query-view_func_name_log.jsp"/>
    </action>

    <action input="update-view_func_name_log.jsp" name="ViewFuncNameLogUpdateForm" txn-code="620100402" check-type="check" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>修改功能大小类对应信息</description>
      <step index="10" bean-name="cn.gwssi.dw.rd.log.txn.TxnViewFuncNameLog" func-name="txn620100402" input-node="record" description="修改功能大小类对应信息"/>
      <forward error-code="success" path="update-view_func_name_log.jsp"/>
      <forward error-code="failure" path="update-view_func_name_log.jsp"/>
    </action>

    <action input="insert-view_func_name_log.jsp" name="ViewFuncNameLogUpdateForm" txn-code="620100403" check-type="check" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>增加功能大小类对应信息</description>
      <step index="10" bean-name="cn.gwssi.dw.rd.log.txn.TxnViewFuncNameLog" func-name="txn620100403" input-node="record" description="增加功能大小类对应信息"/>
      <forward error-code="success" path="insert-view_func_name_log.jsp"/>
      <forward error-code="failure" path="insert-view_func_name_log.jsp"/>
    </action>

    <action input="query-view_func_name_log.jsp" name="ViewFuncNameLogUpdateForm" txn-code="620100404" check-type="check" container="default" txn-type="transaction" re-entry="true" log-flag="true">
      <description>查询功能大小类对应用于修改</description>
      <step index="10" bean-name="cn.gwssi.dw.rd.log.txn.TxnViewFuncNameLog" func-name="txn620100404" input-node="primary-key" output-node="record" description="查询功能大小类对应用于修改"/>
      <forward error-code="success" path="update-view_func_name_log.jsp"/>
      <forward error-code="failure" path="update-view_func_name_log.jsp"/>
    </action>

    <action input="query-view_func_name_log.jsp" name="ViewFuncNameLogDeleteForm" txn-code="620100405" check-type="check" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>删除功能大小类对应信息</description>
      <step index="10" bean-name="cn.gwssi.dw.rd.log.txn.TxnViewFuncNameLog" func-name="txn620100405" input-node="primary-key" description="删除功能大小类对应信息"/>
      <forward error-code="success" path="/script/deletesuccess.jsp"/>
      <forward error-code="failure" path="/script/deletefailure.jsp"/>
    </action>
  </action-mappings>

  <resource>
    <resource-file type="model" file-name="/WEB-INF/resource/jsp-frame/menu-view_func_name_log.xml" description="模板文件"/>
    <resource-file type="jsp" file-name="/dw/rd/log/query-view_func_name_log.jsp" description="查询功能大小类对应列表"/>
    <resource-file type="jsp" file-name="/dw/rd/log/insert-view_func_name_log.jsp" description="增加功能大小类对应信息"/>
    <resource-file type="jsp" file-name="/dw/rd/log/update-view_func_name_log.jsp" description="修改功能大小类对应信息"/>
    <resource-file type="vo-bean" file-name="cn.gwssi.dw.rd.log.vo.ViewFuncNameLogContext" description="应用对应的数据上下文对象"/>
    <resource-file type="vo-bean" file-name="cn.gwssi.dw.rd.log.vo.VoViewFuncNameLog" description="数据表字段对应的VO对象"/>
    <resource-file type="vo-bean" file-name="cn.gwssi.dw.rd.log.vo.VoViewFuncNameLogSelectKey" description="查询条件对应的VO对象"/>
    <resource-file type="vo-bean" file-name="cn.gwssi.dw.rd.log.vo.VoViewFuncNameLogPrimaryKey" description="数据库主键对应的VO对象"/>
  </resource>
</struts-config>

=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/struts/sys_db_user.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struts-config SYSTEM "gwssi-struts.dtd">
<struts-config>
  <menu-name>数据库共享对象管理</menu-name>
  <menu-path>/page/resource/res/runmgr/dbmgr/dbuser/</menu-path>
  <description>服务对象管理</description>
  <form-beans>
    <form-bean name="SysDbUserRowsetForm">
      <description>多记录查询</description>
      <form-property prefix="select-key" name="login_name" 	type="string" size="20" description="用户名"/>
      <form-property prefix="select-key" name="user_type" 	type="string" size="10" description="用户类型"/>
      <form-property prefix="select-key" name="state" 		type="string" size="32" cannull="false" description="密码"/>
      <form-property prefix="select-key" name="showall" 	type="string" size="32" description="临时变量"/>
      <form-property prefix="record" name="sys_db_user_id" type="string" size="32" cannull="false" description="数据库共享对象编号"/>
      <form-property prefix="record" name="login_name" 		type="string" size="32" cannull="false" description="用户名"/>
      <form-property prefix="record" name="user_name" 		type="string" size="32" cannull="false" description="名称"/>
      <form-property prefix="record" name="password" 		type="string" size="32" cannull="false" description="密码"/>
      <form-property prefix="record" name="old_password" 	type="string" size="32" cannull="false" description="旧密码"/>
      <form-property prefix="record" name="create_date" 	type="string" size="10" cannull="false" description="创建日期"/>
      <form-property prefix="record" name="create_by" 		type="string" size="32" cannull="false" description="创建人"/>
      <form-property prefix="record" name="state" 			type="string" size="1"  cannull="false" description="状态"/>
      <form-property prefix="record" name="user_desc" 		type="string" size="1000" cannull="true" description="描述"/>
      <form-property prefix="record" name="user_type" 		type="string" size="10" cannull="true" description="用户类型"/>
      <form-property prefix="record" name="hasConfig" 		type="string" size="10" cannull="true" description="是否配置视图"/>
      <form-property prefix="record" name="grant_table" 	type="string" size="2000" cannull="true" description="被授权的表"/>
      <form-property prefix="record" name="oper" 		type="string" size="10" cannull="true" description="操作"/>
    </form-bean>

  </form-beans>

  <action-mappings>

    <action input="update-sys_db_user.jsp" name="SysDbUserRowsetForm" txn-code="52101002" check-type="check" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>修改数据库共享对象信息</description>
      <step index="10" bean-name="com.gwssi.dw.runmgr.db.txn.TxnSysDbUser" func-name="txn52101002" input-node="record" description="修改数据库共享对象信息"/>
      <forward error-code="success" path="update-sys_db_user.jsp"/>
      <forward error-code="failure" path="update-sys_db_user.jsp"/>
    </action>

    <action input="insert-sys_db_user.jsp" name="SysDbUserRowsetForm" txn-code="52101003" check-type="check" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>增加数据库共享对象信息</description>
      <step index="10" bean-name="com.gwssi.dw.runmgr.db.txn.TxnSysDbUser" func-name="txn52101003" input-node="record" description="增加数据库共享对象信息"/>
      <forward error-code="success" path="insert-sys_db_user.jsp"/>
      <forward error-code="failure" path="insert-sys_db_user.jsp"/>
    </action>

    <action input="update-sys_db_user.jsp" name="SysDbUserRowsetForm" txn-code="52101010" check-type="check" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>初始化数据库共享对象密码</description>
      <step index="10" bean-name="com.gwssi.dw.runmgr.db.txn.TxnSysDbUser" func-name="txn52101010" input-node="record" output-node="record" description="初始化数据库共享对象密码"/>
      <forward error-code="success" path="update-sys_db_user.jsp"/>
      <forward error-code="failure" path="update-sys_db_user.jsp"/>
    </action>
  </action-mappings>
</struts-config>

=== moutainhigh/collections/gratewall/sjzx_ex/webcontent/WEB-INF/struts/xt_ccgl_wjys.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE struts-config SYSTEM "gwssi-struts.dtd">
<struts-config>
  <menu-name>文件映射</menu-name>
  <menu-path>/page/file/manage/</menu-path>
  <description>文件映射</description>
  <form-beans>
    <form-bean name="XtCcglWjysRowsetForm">
      <description>多记录查询</description>
      <form-property prefix="select-key" name="ysbh_pk" type="string" size="32" description="映射编号"/>
      <form-property prefix="record" name="ysbh_pk" type="string" size="32" cannull="false" description="映射编号"/>
      <form-property prefix="record" name="cclbbh_pk" type="string" size="32" cannull="true" description="类别编号ID"/>
      <form-property prefix="record" name="wybs" type="string" size="255" cannull="false" description="唯一标识"/>
      <form-property prefix="record" name="wjmc" type="string" size="255" cannull="false" description="文件名称"/>
      <form-property prefix="record" name="wjzt" type="string" size="1" cannull="true" description="文件状态"/>
      <form-property prefix="record" name="cclj" type="string" size="255" cannull="true" description="存储路径"/>
      <form-property prefix="record" name="cjsj" type="string" size="20" cannull="true" description="创建时间"/>
      <form-property prefix="record" name="scxgsj" type="string" size="20" cannull="true" description="上次修改时间"/>
      <form-property prefix="record" name="bz" type="string" size="255" cannull="true" description="备注"/>
      <form-property prefix="record" name="ywbz" type="string" size="32" cannull="true" description="业务备注"/>
      <form-property prefix="record" name="xm_fk" type="string" size="32" cannull="true" description="项目fk"/>
    </form-bean>

    <form-bean name="XtCcglWjysUpdateForm">
      <description>单记录处理：查询、修改、增加</description>
      <form-property prefix="primary-key" name="ysbh_pk" type="string" size="32" cannull="false" description="映射编号"/>
      <form-property prefix="record" name="ysbh_pk" type="string" size="32" cannull="false" description="映射编号"/>
      <form-property prefix="record" name="cclbbh_pk" type="string" size="32" cannull="true" description="类别编号ID"/>
      <form-property prefix="record" name="wybs" type="string" size="255" cannull="false" description="唯一标识"/>
      <form-property prefix="record" name="wjmc" type="string" size="255" cannull="false" description="文件名称"/>
      <form-property prefix="record" name="wjzt" type="string" size="1" cannull="true" description="文件状态"/>
      <form-property prefix="record" name="cclj" type="string" size="255" cannull="true" description="存储路径"/>
      <form-property prefix="record" name="cjsj" type="string" size="20" cannull="true" description="创建时间"/>
      <form-property prefix="record" name="scxgsj" type="string" size="20" cannull="true" description="上次修改时间"/>
      <form-property prefix="record" name="bz" type="string" size="255" cannull="true" description="备注"/>
      <form-property prefix="record" name="ywbz" type="string" size="32" cannull="true" description="业务备注"/>
      <form-property prefix="record" name="xm_fk" type="string" size="32" cannull="true" description="项目fk"/>
    </form-bean>

    <form-bean name="XtCcglWjysDeleteForm">
      <description>多记录和单记录删除</description>
      <form-property prefix="primary-key" name="ysbh_pk" type="string" size="32" cannull="false" description="映射编号"/>
    </form-bean>
    
    <form-bean name="Xt_ccgl_downLoadForm">
      <description>系统存储文件下载</description>
      <form-property prefix="primary-key" name="ysbh_pk" type="int" cannull="false" description="文件映射编号"/>
      <form-property prefix="primary-key" name="wjmc" type="string" size="60" cannull="false" description="文件名称"/>
      <form-property prefix="primary-key" name="logFlag" type="string" size="10" cannull="false" description="标志"/>
      <form-property prefix="record" name="cclbbh_pk" type="int" cannull="false" description="文件类别编号"/>
      <form-property prefix="record" name="wjmc" type="string" size="60" cannull="false" description="文件名称"/>
      <form-property prefix="record" name="cclj" type="string" cannull="true" description="存储路径"/>
      <form-property prefix="record" name="wybs" type="int" size="255" cannull="false" description="唯一标识"/>      
    </form-bean>
  </form-beans>

  <action-mappings>
    <action input="query-xt_ccgl_wjys.jsp" name="XtCcglWjysRowsetForm" txn-code="604060101" check-type="public" container="default" txn-type="transaction" re-entry="true" log-flag="true">
      <description>查询文件映射列表</description>
      <step index="10" bean-name="com.gwssi.file.manage.txn.TxnXtCcglWjys" func-name="txn604060101" input-node="select-key" output-node="record" description="查询文件映射列表"/>
      <forward error-code="success" path="query-xt_ccgl_wjys.jsp"/>
      <forward error-code="failure" path="query-xt_ccgl_wjys.jsp"/>
    </action>

    <action input="update-xt_ccgl_wjys.jsp" name="XtCcglWjysUpdateForm" txn-code="604060102" check-type="public" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>修改文件映射信息</description>
      <step index="10" bean-name="com.gwssi.file.manage.txn.TxnXtCcglWjys" func-name="txn604060102" input-node="record" description="修改文件映射信息"/>
      <forward error-code="success" path="update-xt_ccgl_wjys.jsp"/>
      <forward error-code="failure" path="update-xt_ccgl_wjys.jsp"/>
    </action>

    <action input="insert-xt_ccgl_wjys.jsp" name="XtCcglWjysUpdateForm" txn-code="604060103" check-type="public" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>增加文件映射信息</description>
      <step index="10" bean-name="com.gwssi.file.manage.txn.TxnXtCcglWjys" func-name="txn604060103" input-node="record" description="增加文件映射信息"/>
      <forward error-code="success" path="insert-xt_ccgl_wjys.jsp"/>
      <forward error-code="failure" path="insert-xt_ccgl_wjys.jsp"/>
    </action>

    <action input="query-xt_ccgl_wjys.jsp" name="XtCcglWjysUpdateForm" txn-code="604060104" check-type="public" container="default" txn-type="transaction" re-entry="true" log-flag="true">
      <description>查询文件映射用于修改</description>
      <step index="10" bean-name="com.gwssi.file.manage.txn.TxnXtCcglWjys" func-name="txn604060104" input-node="primary-key" output-node="record" description="查询文件映射用于修改"/>
      <forward error-code="success" path="update-xt_ccgl_wjys.jsp"/>
      <forward error-code="failure" path="update-xt_ccgl_wjys.jsp"/>
    </action>

    <action input="query-xt_ccgl_wjys.jsp" name="XtCcglWjysDeleteForm" txn-code="604060105" check-type="public" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>删除文件映射信息</description>
      <step index="10" bean-name="com.gwssi.file.manage.txn.TxnXtCcglWjys" func-name="txn604060105" input-node="primary-key" description="删除文件映射信息"/>
      <forward error-code="success" path="/script/deletesuccess.jsp"/>
      <forward error-code="failure" path="/script/deletefailure.jsp"/>
    </action>
    
    <action input="query-xt_ccgl_wjlb.jsp" name="Xt_ccgl_downLoadForm" txn-code="604050209" check-type="public" container="default" txn-type="transaction" re-entry="false" log-flag="true">
      <description>下载文件</description>
      <step index="10" bean-name="com.gwssi.file.manage.txn.TxnXtCcglWjys" func-name="txn604050209" input-node="primary-key" output-node="record"/>
      <forward error-code="success" path="/script/deletesuccess.jsp" redirect="false"/>
      <forward error-code="failure" path="/script/deletefailure.jsp" redirect="false"/>
    </action>
  </action-mappings>

  <resource>
    <resource-file type="model" file-name="/WEB-INF/resource/jsp-frame/menu-xt_ccgl_wjys.xml" description="模板文件"/>
    <resource-file type="jsp" file-name="/page/file/manage/query-xt_ccgl_wjys.jsp" description="查询文件映射列表"/>
    <resource-file type="jsp" file-name="/page/file/manage/insert-xt_ccgl_wjys.jsp" description="增加文件映射信息"/>
    <resource-file type="jsp" file-name="/page/file/manage/update-xt_ccgl_wjys.jsp" description="修改文件映射信息"/>
    <resource-file type="vo-bean" file-name="com.gwssi.file.manage.vo.XtCcglWjysContext" description="应用对应的数据上下文对象"/>
    <resource-file type="vo-bean" file-name="com.gwssi.file.manage.vo.VoXtCcglWjys" description="数据表字段对应的VO对象"/>
    <resource-file type="vo-bean" file-name="com.gwssi.file.manage.vo.VoXtCcglWjysSelectKey" description="查询条件对应的VO对象"/>
    <resource-file type="vo-bean" file-name="com.gwssi.file.manage.vo.VoXtCcglWjysPrimaryKey" description="数据库主键对应的VO对象"/>
  </resource>
</struts-config>
